version: '2'
services:
  nearmap_ai:
    build: .
    environment:
      - API_KEY=${API_KEY}
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
      - GRANT_SUDO=yes
      - GEN_CERT=yes
      - JUPYTER_LAB_ENABLE=yes
    user: root
    volumes:
      - /mnt/DATA/data_michaelbewley/Development/datascience/nearmap-ai-user-guides/data:/home/jovyan/data
      - /mnt/DATA2/offline_exports/processed:/home/jovyan/offline_exports/processed
    entrypoint: [
        "start.sh",
        "python", "/home/jovyan/nearmap-ai-user-guides/scripts/ai_offline_parcel.py",
        "--parcel-dir", "/home/jovyan/data/parcels/DS-7498_TM002-us-tree-cover",
        "--output-dir", "/home/jovyan/offline_exports/processed/DS-7498_TM002-us-tree-cover",
        "--packs", "building", "vegetation",
        "--country", "us",
        "--primary-decision", "largest_intersection",
        "--workers",  "32",
        "--compress-cache",
        "--log-level", "INFO",
        "--include-parcel-geometry",
        "--save-features",
    ]
