version: '2'
services:
  nearmap_ai:
    build: .
    environment:
      - API_KEY=${API_KEY}
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
      - GRANT_SUDO=yes
      - GEN_CERT=yes
      - JUPYTER_LAB_ENABLE=yes
    user: root
    volumes:
      - <local path to data directory>:/home/jovyan/data
    entrypoint: [
        "pytest", "/home/jovyan/nearmap-ai-user-guides",
    ]