version: '2'
services:
  nmaipy:
    build: .
    environment:
      - API_KEY=${API_KEY}
      - NB_UID=${NB_UID}
      - NB_GID=${NB_GID}
      - GRANT_SUDO=yes
      - GEN_CERT=yes
      - JUPYTER_LAB_ENABLE=yes
    user: root
    volumes:
      - <local path to data directory>:/home/jovyan/data
    entrypoint: [
        "start.sh",
        "python", "/home/jovyan/nearmap-ai-user-guides/scripts/ai_offline_parcel.py",
        "--parcel-dir", "/home/jovyan/data/<path to parcels>",
        "--output-dir", "/home/jovyan/data/<path to results>",
        "--packs", "building", "building_char", "roof_char", "roof_cond", "pool", "solar", "trampoline", "construction", "vegetation", "surfaces",
        "--country", "us",
        "--primary-decision", "largest_intersection",
        "--workers",  "32",
        "--compress-cache",
        "--log-level", "INFO",
        "--include-parcel-geometry",
        "--save-features",
    ]
